---
globalSettings:
  network-server:
    timeout: 60 #seconds
    lock: 20 #minutes
    gan-server:
      ipAdress:
        min:
        max:
      connectionType:
        - gan-server
        - wan-server
    wan-server:
      ipAdress:
        min:
        max:
      connectionType:
        - gan-server
        - man-server
    man-server:
      ipAdress:
        min:
        max:
      connectionType:
        - wan-server
        - player-router
  service-server:
    example:
  player-router:
    connectionType:
      - man-server

network-server:
  gan-server:
    - name: Europa          #Bezeichnung des GAN-Servers
      darknet: false        #Ist GAN ein Darknet Server
      ganConnect:           #Verbindung zu anderen GAN-Servern
        - Asien       
        - Nordamerika
      - wan-server:         #WAN-Server innerhalb des darüberstehenden GAN-Server
        name: Deutschland   
        man-server:         #MAN-Server innerhalb des darüberstehenden WAN-Server
          name:
            - Berlin
            - München
            - Hamburg
      - wan-server:
        name: Finnland
        man-server:
          name:
            - Helsinki
            - Espoo
            - Tamepere
      - wan-server:
        name: Spanien
        man-server:
          name:
            - Madrid
            - Barcelona
            - Valencia

    - name: Asien
      darknet: false
      ganConnect:          
        - Europa       
        - Australien
      - wan-server:
        name: China
        man-server:
          name:
            - Peking
            - Shenzhen
            - Shanghai
      - wan-server:
        name: Russland
        man-server:
          name:
            - Moskau
            - Nowosibirsk
            - Sankt Petersburg
      - wan-server:
        name: Indien
        man-server:
          name:
            - Delhi
            - Mumbai
            - Kalkutta

    - name: Australien
      darknet: false
      ganConnect:         
        - Asien       
        - Afrika
      - wan-server:
        name: Queensland
        man-server:
          name:
            - Brisbane
      - wan-server:
        name: New South Wales
        man-server:
          name:
            - Sydney
      - wan-server:
        name: Western Aust
        man-server:
          name:
            - Perth

    - name: Afrika
      darknet: false
      ganConnect:          
        - Australien       
        - Südamerika
      - wan-server:
        name: Ägypten
        man-server:
          name:
            - Kairo
            - Gizeh
            - Alexandria
      - wan-server:
        name: Algerien
        man-server:
          name:
            - Agier
            - Oran
            - Constantine
      - wan-server:
        name: Südafrika
        man-server:
          name:
            - Kapstadt
            - Durban
            - Johannesburg

    - name: Südamerika
      darknet: false
      ganConnect:         
        - Afrika       
        - Nordamerika
      - wan-server:
        name: Brasilien
        man-server:
          name:
            - Rio de Janeiro
            - Sao Paulo
            - Manaus
      - wan-server:
        name: Peru
        man-server:
          name:
            - Cusco
            - Lima
            - Arequipa
      - wan-server:
        name: Argentinien
        man-server:
          name:
            - Buenos Aires
            - Mendoza
            - Salta

    - name: Nordamerika
      darknet: false
      ganConnect:          
        - Europa       
        - Süddamerika
      - wan-server:
        name: Kanada
        man-server:
          name:
            - Montreal
            - Toronto
            - Vancouver
      - wan-server:
        name: USA
        man-server:
          name:
            - New York
            - Los Angeles
            - Chicago
      - wan-server:
        name: Mexico
        man-server:
          name:
            - Mexico
            - Puebla
            - Tijuana
    
      #Darknet-Server
    - name: Proxima Centauri
      darknet: true
      ganConnect:          #Verbindungen bestimmen !!!
        - #platzhalter       
        - #platzhalter
      - wan-server:
        name: Sun
        man-server:
          name:
            - Mercury
            - Venus
            - Earth
            - Mars
      - wan-server:
        name: Sun
        man-server:
          name:
            - Jupiter
            - Saturn
            - Uranus
            - Neptune
            - Pluto
      